import Foundation

/// A fixed gallery of hand-picked, resolution-verified NASA assets. Used where
/// the live search is unreliable (planetary imagery). Each asset resolves to its
/// `~orig` (maximum-resolution) file, with `ImageCache` falling back to the
/// thumbnail if needed. Rotates daily for variety while staying deterministic so
/// the prefetcher caches exactly what's shown.
struct StaticGallerySource: ImageSource {
    let id: String
    let name: String
    let subtitle: String
    let symbol: String
    let accentHex: UInt32
    var typicalResolution: ResolutionHint {
        if assets.contains(where: { $0.resolution == .uhd }) { return .uhd }
        if assets.contains(where: { $0.resolution == .hd }) { return .hd }
        return .sd
    }
    let assets: [Asset]

    struct Asset {
        let identifier: String
        let title: String
        let credit: String
        let explanation: String
        let date: Date?
        let pageURL: URL?
        let imageURL: URL
        let thumbURL: URL?
        let resolution: ResolutionHint

        init(title: String,
             nasaID: String,
             credit: String,
             explanation: String,
             dateString: String? = nil,
             resolution: ResolutionHint = .uhd) {
            let base = "https://images-assets.nasa.gov/image/\(nasaID)/\(nasaID)"
            self.identifier = nasaID
            self.title = title
            self.credit = credit
            self.explanation = explanation
            self.date = dateString.flatMap { CaelumDates.ymd.date(from: $0) }
            self.pageURL = URL(string: "https://images.nasa.gov/details/\(nasaID)")
            self.imageURL = URL(string: base + "~orig.jpg")!
            self.thumbURL = URL(string: base + "~medium.jpg")
            self.resolution = resolution
        }

        init(identifier: String,
             title: String,
             credit: String,
             explanation: String,
             imageURL: String,
             thumbURL: String? = nil,
             pageURL: String? = nil,
             dateString: String? = nil,
             resolution: ResolutionHint = .uhd) {
            self.identifier = identifier
            self.title = title
            self.credit = credit
            self.explanation = explanation
            self.date = dateString.flatMap { CaelumDates.ymd.date(from: $0) }
            self.pageURL = pageURL.flatMap(URL.init(string:))
            self.imageURL = URL(string: imageURL)!
            self.thumbURL = thumbURL.flatMap(URL.init(string:))
            self.resolution = resolution
        }
    }

    func fetchRecent(limit: Int) async throws -> [CosmicImage] {
        guard !assets.isEmpty else { throw SourceError.empty }
        let offset = Int(Date().timeIntervalSince1970 / 86_400) % assets.count
        let rotated = Array(assets[offset...] + assets[..<offset])
        let images = rotated.map { asset in
            CosmicImage(
                id: "\(id)-\(asset.identifier)",
                title: asset.title,
                credit: asset.credit,
                explanation: asset.explanation,
                date: asset.date,
                sourceID: id,
                pageURL: asset.pageURL,
                imageURL: asset.imageURL,
                thumbURL: asset.thumbURL,
                isVideo: false,
                resolution: asset.resolution)
        }
        return Array(images.prefix(max(limit, 1)))
    }
}

extension StaticGallerySource {
    /// Deep Space — stable 4K+ observatory classics instead of daily feed noise.
    static let deep = StaticGallerySource(
        id: "deep", name: "Deep Space", subtitle: "Nebulae & galaxies",
        symbol: "sparkle.magnifyingglass", accentHex: 0xB8C0FF,
        assets: [
            .init(identifier: "weic2205a",
                  title: "Cosmic Cliffs of Carina",
                  credit: "NASA, ESA, CSA, STScI",
                  explanation: "Webb's infrared view of the star-forming edge of NGC 3324 in the Carina Nebula.",
                  imageURL: "https://cdn.esawebb.org/archives/images/large/weic2205a.jpg",
                  thumbURL: "https://cdn.esawebb.org/archives/images/screen/weic2205a.jpg",
                  pageURL: "https://esawebb.org/images/weic2205a/"),
            .init(identifier: "heic1509a",
                  title: "Pillars of Creation",
                  credit: "NASA, ESA, Hubble Heritage Team",
                  explanation: "Hubble's high-resolution visible-light portrait of the Pillars of Creation in the Eagle Nebula.",
                  imageURL: "https://cdn.esahubble.org/archives/images/large/heic1509a.jpg",
                  thumbURL: "https://cdn.esahubble.org/archives/images/screen/heic1509a.jpg",
                  pageURL: "https://esahubble.org/images/heic1509a/"),
            .init(identifier: "heic0611b",
                  title: "Hubble Ultra Deep Field",
                  credit: "NASA / ESA / Hubble",
                  explanation: "Thousands of galaxies fill one of Hubble's deepest views of the universe.",
                  imageURL: "https://cdn.esahubble.org/archives/images/large/heic0611b.jpg",
                  thumbURL: "https://cdn.esahubble.org/archives/images/screen/heic0611b.jpg",
                  pageURL: "https://esahubble.org/images/heic0611b/"),
            .init(identifier: "weic2609c",
                  title: "A Little Red Dot",
                  credit: "ESA/Webb, NASA & CSA",
                  explanation: "Webb looks across cosmic time toward Abell 2744 and very distant early-universe objects.",
                  imageURL: "https://cdn.esawebb.org/archives/images/large/weic2609c.jpg",
                  thumbURL: "https://cdn.esawebb.org/archives/images/screen/weic2609c.jpg",
                  pageURL: "https://esawebb.org/images/weic2609c/"),
            .init(identifier: "weic2212a",
                  title: "Tarantula Nebula",
                  credit: "NASA, ESA, CSA, STScI",
                  explanation: "Webb's near-infrared view of star-forming region 30 Doradus.",
                  imageURL: "https://cdn.esawebb.org/archives/images/large/weic2212a.jpg",
                  thumbURL: "https://cdn.esawebb.org/archives/images/screen/weic2212a.jpg",
                  pageURL: "https://esawebb.org/images/weic2212a/"),
            .init(identifier: "weic2303a",
                  title: "Rho Ophiuchi Cloud Complex",
                  credit: "NASA, ESA, CSA, STScI",
                  explanation: "Webb's multicolored view of a nearby star-forming region with dust and nebulosity.",
                  imageURL: "https://cdn.esawebb.org/archives/images/large/weic2303a.jpg",
                  thumbURL: "https://cdn.esawebb.org/archives/images/screen/weic2303a.jpg",
                  pageURL: "https://esawebb.org/images/weic2303a/"),
            .init(identifier: "heic0601a",
                  title: "Orion Nebula",
                  credit: "NASA, ESA, Hubble Heritage Team",
                  explanation: "Hubble's expansive mosaic of the Orion Nebula reveals stellar nursery details.",
                  imageURL: "https://cdn.esahubble.org/archives/images/large/heic0601a.jpg",
                  thumbURL: "https://cdn.esahubble.org/archives/images/screen/heic0601a.jpg",
                  pageURL: "https://esahubble.org/images/heic0601a/"),
            .init(identifier: "heic0506a",
                  title: "Whirlpool Galaxy",
                  credit: "NASA, ESA, Hubble Heritage Team",
                  explanation: "Hubble's stunning face-on spiral galaxy with sharp dust lanes and golden star-forming regions.",
                  imageURL: "https://cdn.esahubble.org/archives/images/large/heic0506a.jpg",
                  thumbURL: "https://cdn.esahubble.org/archives/images/screen/heic0506a.jpg",
                  pageURL: "https://esahubble.org/images/heic0506a/"),
            .init(identifier: "eso1303a",
                  title: "Blue Star in a Dark Nebula",
                  credit: "ESO/Digitized Sky Survey 2",
                  explanation: "A brilliant blue-white star HD 97300 ignites a glowing reflection nebula against dense dark clouds in the Chamaeleon star-forming region.",
                  imageURL: "https://www.eso.org/public/archives/images/large/eso1303a.jpg",
                  thumbURL: "https://www.eso.org/public/archives/images/screen/eso1303a.jpg",
                  pageURL: "https://www.eso.org/public/images/eso1303a/",
                  dateString: "2013-03-27"),
            .init(identifier: "eso1605a",
                  title: "IC 4592 — The Blue Horsehead Nebula",
                  credit: "ESO/Digitized Sky Survey 2",
                  explanation: "The hot blue star Nu Scorpii paints a vast reflection nebula in the constellation Scorpius, surrounding the ghostly Blue Horsehead cloud at 9.8K resolution.",
                  imageURL: "https://www.eso.org/public/archives/images/large/eso1605a.jpg",
                  thumbURL: "https://www.eso.org/public/archives/images/screen/eso1605a.jpg",
                  pageURL: "https://www.eso.org/public/images/eso1605a/",
                  dateString: "2016-02-10"),
            .init(identifier: "eso1701a",
                  title: "Rho Ophiuchi Star-Forming Tendrils",
                  credit: "ESO/S. Guisard",
                  explanation: "A dramatic wide-field view of the Rho Ophiuchi molecular cloud — one of the nearest stellar nurseries — with orange dust filaments and blue reflection nebulae.",
                  imageURL: "https://www.eso.org/public/archives/images/large/eso1701a.jpg",
                  thumbURL: "https://www.eso.org/public/archives/images/screen/eso1701a.jpg",
                  pageURL: "https://www.eso.org/public/images/eso1701a/",
                  dateString: "2017-01-11"),
            .init(identifier: "eso1740a",
                  title: "The Lagoon Nebula in Infrared",
                  credit: "ESO/VISTA/J. Emerson",
                  explanation: "VISTA's 17K infrared panorama of the Lagoon Nebula NGC 6523 strips away the dust to reveal thousands of young stars embedded in glowing pink gas.",
                  imageURL: "https://www.eso.org/public/archives/images/large/eso1740a.jpg",
                  thumbURL: "https://www.eso.org/public/archives/images/screen/eso1740a.jpg",
                  pageURL: "https://www.eso.org/public/images/eso1740a/",
                  dateString: "2017-10-25"),
            .init(identifier: "eso1913a",
                  title: "Seagull Nebula over the Southern Milky Way",
                  credit: "ESO/F. Kamphues",
                  explanation: "A sweeping 20K mosaic of the Seagull Nebula IC 2177 in Monoceros, with wings of ionised hydrogen blazing pink and orange across a star-rich Milky Way field.",
                  imageURL: "https://www.eso.org/public/archives/images/large/eso1913a.jpg",
                  thumbURL: "https://www.eso.org/public/archives/images/screen/eso1913a.jpg",
                  pageURL: "https://www.eso.org/public/images/eso1913a/",
                  dateString: "2019-04-24"),
            .init(identifier: "eso1526a",
                  title: "Star Cluster NGC 1850 in the LMC",
                  credit: "ESO",
                  explanation: "A young double star cluster blazes at the heart of the Large Magellanic Cloud, surrounded by wisps of nebulosity and older surrounding stars.",
                  imageURL: "https://www.eso.org/public/archives/images/large/eso1526a.jpg",
                  thumbURL: "https://www.eso.org/public/archives/images/screen/eso1526a.jpg",
                  pageURL: "https://www.eso.org/public/images/eso1526a/",
                  dateString: "2015-09-23"),
            .init(identifier: "weic2316a",
                  title: "Rho Ophiuchi — Webb's Star-Birth Portrait",
                  credit: "NASA, ESA, CSA, STScI, K. Pontoppidan (STScI)",
                  explanation: "Webb's first-anniversary image: the nearest stellar nursery in exquisite 12K infrared detail, with jets of pink hydrogen slicing dark filaments and young sun-like stars.",
                  imageURL: "https://cdn.esawebb.org/archives/images/large/weic2316a.jpg",
                  thumbURL: "https://cdn.esawebb.org/archives/images/screen/weic2316a.jpg",
                  pageURL: "https://esawebb.org/images/weic2316a/",
                  dateString: "2023-07-12"),
            .init(identifier: "eso2209a",
                  title: "Heart of the Tarantula — 30 Doradus",
                  credit: "ESO/M.-R. Cioni/VISTA Magellanic Cloud survey",
                  explanation: "A multiwavelength composite of the Tarantula Nebula 30 Doradus, blending optical and infrared data to reveal the most luminous star-forming region in the Local Group.",
                  imageURL: "https://www.eso.org/public/archives/images/large/eso2209a.jpg",
                  thumbURL: "https://www.eso.org/public/archives/images/screen/eso2209a.jpg",
                  pageURL: "https://www.eso.org/public/images/eso2209a/",
                  dateString: "2022-09-07"),
        ])

    /// Earth from orbit — no people, no press-room photos, high pixel count.
    static let earth = StaticGallerySource(
        id: "earth", name: "Earth from Space", subtitle: "Orbit & lunar views",
        symbol: "globe.europe.africa.fill", accentHex: 0x5EF2B0,
        assets: [
            .init(title: "Moonlit Pacific from the ISS", nasaID: "iss071e456772",
                  credit: "NASA",
                  explanation: "Moon glint, airglow and stars photographed from the International Space Station above the Pacific Ocean.",
                  dateString: "2024-07-18"),
            .init(title: "Aurora from the Station", nasaID: "iss058e005282",
                  credit: "NASA",
                  explanation: "Earth's limb and aurora beneath the International Space Station's solar arrays.",
                  dateString: "2019-01-19"),
            .init(title: "Orbital Star Trails", nasaID: "iss074e0319988",
                  credit: "NASA/JAXA",
                  explanation: "A long-duration exposure from the ISS turns city lights and stars into streaks above Earth.",
                  dateString: "2026-02-19"),
            .init(title: "Earthset from Orion", nasaID: "art002e009288",
                  credit: "NASA",
                  explanation: "Earth drops behind the Moon as photographed from the Orion spacecraft.",
                  dateString: "2026-04-01"),
            .init(title: "Blue Marble 2012", nasaID: "PIA18033",
                  credit: "NASA",
                  explanation: "A detailed full-disk composite of Earth showing oceans, continents, and atmosphere.",
                  dateString: "2012-06-01"),
            .init(title: "Black Marble", nasaID: "GSFC_20171208_Archive_e001591",
                  credit: "NASA/NOAA",
                  explanation: "A global night-time composite showing city lights, auroras, and natural luminescence.",
                  dateString: "2017-12-08"),
            .init(title: "Artemis Era Earthrise", nasaID: "art002e009280b",
                  credit: "NASA",
                  explanation: "A crescent Earth framed through the window of the Orion spacecraft.",
                  dateString: "2026-04-01"),
            .init(title: "Aurora and City Lights", nasaID: "iss029e012564",
                  credit: "NASA",
                  explanation: "Aurora borealis and night-side city lights illuminate Earth from the ISS vantage point.",
                  dateString: "2012-09-01"),
        ])

    /// Solar System — verified high-resolution planetary imagery.
    static let solar = StaticGallerySource(
        id: "solar", name: "Solar System", subtitle: "Planets & moons",
        symbol: "sun.max.fill", accentHex: 0xFFD166,
        assets: [
            .init(title: "Jupiter's Great Red Spot", nasaID: "PIA01384",
                  credit: "NASA/JPL",
                  explanation: "Voyager 1's high-resolution color view of Jupiter and the Great Red Spot."),
            .init(title: "The Rich Colors of Pluto", nasaID: "PIA19952",
                  credit: "NASA/JHUAPL/SwRI",
                  explanation: "New Horizons' enhanced-color portrait of Pluto from its 2015 flyby.",
                  dateString: "2015-07-14"),
            .init(title: "The Day the Earth Smiled", nasaID: "PIA17172",
                  credit: "NASA/JPL-Caltech/SSI",
                  explanation: "A 9,000-pixel Cassini mosaic of Saturn backlit by the Sun, with Earth as a faint dot."),
            .init(title: "Saturn Noodle Mosaic", nasaID: "PIA21617",
                  credit: "NASA/JPL-Caltech/SSI",
                  explanation: "Cassini's Grand Finale mosaic reveals Saturn's north polar vortex, hexagon and cloud bands."),
            .init(title: "95 Minutes Over Jupiter", nasaID: "PIA21967",
                  credit: "NASA/JPL-Caltech/SwRI/MSSS",
                  explanation: "A dramatic 16K-wide JunoCam sequence captures Jupiter's cloud patterns and colors.",
                  dateString: "2018-06-01"),
            .init(title: "Juno Captures Brown Barge", nasaID: "PIA22939",
                  credit: "NASA/JPL-Caltech/SwRI/MSSS",
                  explanation: "A 6K Juno observation of a prominent brown feature in Jupiter's atmosphere.",
                  dateString: "2019-07-01"),
            .init(title: "Turbulence in Jupiter's Atmosphere", nasaID: "PIA26595",
                  credit: "NASA/JPL-Caltech/SwRI/MSSS",
                  explanation: "A recent 6.8K Juno image of dramatic cloud formations in Jupiter's upper atmosphere.",
                  dateString: "2023-03-01"),
            .init(title: "Pluto's Twilight Zone", nasaID: "PIA20727",
                  credit: "NASA/JHUAPL/SwRI",
                  explanation: "New Horizons captures Pluto's crescent with atmospheric haze and subtle color contrasts.",
                  dateString: "2015-07-14"),
        ])

    /// Spacecraft — orbital hardware and ships, curated away from people.
    static let stations = StaticGallerySource(
        id: "stations", name: "Spacecraft", subtitle: "Orion, ISS & satellites",
        symbol: "antenna.radiowaves.left.and.right", accentHex: 0xFF8A5E,
        assets: [
            .init(title: "CubeSats Deploy from the ISS", nasaID: "iss074e0301636",
                  credit: "NASA",
                  explanation: "A trio of CubeSats deploys into Earth orbit from the International Space Station.",
                  dateString: "2026-02-03"),
            .init(title: "Orion Approaches the Moon", nasaID: "art001e000269",
                  credit: "NASA",
                  explanation: "The Orion spacecraft approaches the Moon during Artemis I's outbound powered flyby.",
                  dateString: "2022-11-21"),
            .init(title: "Orion Between Earth and Moon", nasaID: "art001e001713",
                  credit: "NASA",
                  explanation: "Orion's solar array wing cuts between Earth and Moon during Artemis I.",
                  dateString: "2022-12-02"),
            .init(title: "Orion Looks Back", nasaID: "art001e002186",
                  credit: "NASA",
                  explanation: "The Orion spacecraft looks back at the Moon late in the Artemis I mission.",
                  dateString: "2022-12-08"),
            .init(title: "Dragon CRS-9 Approaches the ISS", nasaID: "iss048e042025",
                  credit: "NASA",
                  explanation: "The SpaceX Dragon cargo spacecraft approaches the International Space Station for docking.",
                  dateString: "2016-07-03"),
            .init(title: "Moonlit ISS Solar Arrays", nasaID: "iss073e0850593",
                  credit: "NASA",
                  explanation: "ISS hardware glows with an unusual violet hue under moonlight in Earth orbit.",
                  dateString: "2024-01-15"),
            .init(title: "Voyager Enters Interstellar Space", nasaID: "PIA17462",
                  credit: "NASA/JPL",
                  explanation: "An 8K NASA/JPL concept depicting the historic Voyager probe leaving our solar system.",
                  dateString: "2012-09-01"),
            .init(title: "Perseverance Rover on Mars", nasaID: "PIA21635",
                  credit: "NASA/JPL-Caltech",
                  explanation: "A photorealistic concept rendering of the Mars 2020 Perseverance rover at work on the Martian surface.",
                  dateString: "2017-07-01"),
        ])

    /// Science-fiction wallpaper art, curated toward Interstellar-style ships,
    /// black holes, wormholes, and planet-scale shots with no character close-ups.
    static let interstellar = StaticGallerySource(
        id: "interstellar", name: "Sci-Fi", subtitle: "Interstellar & beyond",
        symbol: "hurricane", accentHex: 0x8B7CFF,
        assets: [
            .init(identifier: "fiction-gargantua-endurance",
                  title: "Gargantua and the Endurance",
                  credit: "4K Wallpapers",
                  explanation: "A high-resolution Interstellar-inspired view of the Endurance crossing Gargantua's accretion disk.",
                  imageURL: "https://4kwallpapers.com/images/wallpapers/gargantua-endurance-5120x3662-25445.jpg",
                  thumbURL: "https://4kwallpapers.com/images/walls/thumbs_2t/25445.jpg",
                  pageURL: "https://4kwallpapers.com/space/gargantua-endurance-25445.html"),
            .init(identifier: "fiction-endurance-gargantua-flyby",
                  title: "Endurance Near Gargantua",
                  credit: "WallpaperCat",
                  explanation: "A 4K Interstellar frame-style composition with the Endurance silhouetted against Gargantua's bright disk.",
                  imageURL: "https://wallpapercat.com/w/full/c/f/2/2130632-3840x2160-desktop-4k-gargantua-interstellar-wallpaper-photo.jpg",
                  pageURL: "https://wallpapercat.com/gargantua-interstellar-wallpapers"),
            .init(identifier: "fiction-gargantua-event-horizon",
                  title: "Gargantua Event Horizon",
                  credit: "WallpaperCat",
                  explanation: "A cinematic close view of Gargantua's warped light and accretion disk.",
                  imageURL: "https://wallpapercat.com/w/full/9/f/1/2130788-3840x1607-desktop-dual-screen-gargantua-interstellar-wallpaper.jpg",
                  pageURL: "https://wallpapercat.com/gargantua-interstellar-wallpapers"),
            .init(identifier: "fiction-wormhole-approach",
                  title: "Wormhole Approach",
                  credit: "WallpaperCat",
                  explanation: "A 4K wormhole view with distorted starlight and no foreground characters.",
                  imageURL: "https://wallpapercat.com/w/full/9/6/9/2132185-3840x2160-desktop-4k-wormhole-interstellar-wallpaper-photo.jpg",
                  pageURL: "https://wallpapercat.com/wormhole-interstellar-wallpapers"),
            .init(identifier: "fiction-endurance-storm-world",
                  title: "Endurance Above a Storm World",
                  credit: "WallpaperCat",
                  explanation: "A wide, high-resolution spacecraft shot with the Endurance suspended over a turbulent alien world.",
                  imageURL: "https://wallpapercat.com/w/full/3/f/1/306211-3840x2160-desktop-4k-interstellar-background-image.jpg",
                  pageURL: "https://wallpapercat.com/interstellar-wallpapers"),
            .init(identifier: "fiction-gargantua-singularity",
                  title: "Gargantua Singularity",
                  credit: "WallpaperCat",
                  explanation: "A stark black-hole composition centered on Gargantua's luminous ring.",
                  imageURL: "https://wallpapercat.com/w/full/d/e/d/2129817-3840x2160-desktop-4k-gargantua-interstellar-background.jpg",
                  pageURL: "https://wallpapercat.com/gargantua-interstellar-wallpapers"),
            .init(identifier: "fiction-black-hole-satellite",
                  title: "Black Hole Satellite View",
                  credit: "Vadim Sadovski / 4K Wallpapers",
                  explanation: "A 5K deep-space spacecraft scene looking toward a black hole and its surrounding disk.",
                  imageURL: "https://4kwallpapers.com/images/wallpapers/black-hole-gargantua-interstellar-satellite-outer-space-5k-5200x3400-8249.jpg",
                  thumbURL: "https://4kwallpapers.com/images/walls/thumbs_2t/8249.jpg",
                  pageURL: "https://4kwallpapers.com/space/black-hole-gargantua-interstellar-satellite-outer-space-5k-8249.html"),
            .init(identifier: "fiction-gargantua-blue-lens",
                  title: "Gargantua Blue Lens",
                  credit: "Sam K / 4K Wallpapers",
                  explanation: "A 5K black-hole render with blue-white lensing and a clean wallpaper silhouette.",
                  imageURL: "https://4kwallpapers.com/images/wallpapers/gargantua-black-5200x3250-9621.jpg",
                  thumbURL: "https://4kwallpapers.com/images/walls/thumbs_2t/9621.jpg",
                  pageURL: "https://4kwallpapers.com/space/gargantua-black-9621.html"),
            .init(identifier: "fiction-gargantua-close-pass",
                  title: "Gargantua Close Pass",
                  credit: "WallpaperCat",
                  explanation: "A clean 4K black-hole pass with a bright accretion disk and a small spacecraft silhouette.",
                  imageURL: "https://wallpapercat.com/w/full/5/a/0/306069-3840x2160-desktop-4k-interstellar-wallpaper.jpg",
                  pageURL: "https://wallpapercat.com/interstellar-wallpapers"),
            .init(identifier: "fiction-gargantua-minimal-ring",
                  title: "Gargantua Minimal Ring",
                  credit: "WallpaperCat",
                  explanation: "A stark 4K Gargantua-style black-hole ring against a deep black star field.",
                  imageURL: "https://wallpapercat.com/w/full/6/f/b/306081-3840x2160-desktop-4k-interstellar-wallpaper.jpg",
                  pageURL: "https://wallpapercat.com/interstellar-wallpapers"),
            // --- Verified ESO/EHT open-access imagery ---
            .init(identifier: "eso1907a",
                  title: "First Photograph of a Black Hole",
                  credit: "Event Horizon Telescope Collaboration/ESO",
                  explanation: "Humanity's first direct image of a black hole: the 6.5-billion-solar-mass giant at the centre of galaxy M87, captured at 7.4K resolution by the Event Horizon Telescope.",
                  imageURL: "https://www.eso.org/public/archives/images/large/eso1907a.jpg",
                  thumbURL: "https://www.eso.org/public/archives/images/screen/eso1907a.jpg",
                  pageURL: "https://www.eso.org/public/images/eso1907a/",
                  dateString: "2019-04-10"),
            .init(identifier: "eso1735a",
                  title: "Dust Rings of Proxima Centauri",
                  credit: "ESO/M. Kornmesser",
                  explanation: "An 8K artist's impression of the debris disk surrounding Proxima Centauri — our nearest stellar neighbour — a vast dust ring that may hide further undiscovered worlds.",
                  imageURL: "https://www.eso.org/public/archives/images/large/eso1735a.jpg",
                  thumbURL: "https://www.eso.org/public/archives/images/screen/eso1735a.jpg",
                  pageURL: "https://www.eso.org/public/images/eso1735a/",
                  dateString: "2017-11-03"),
            .init(identifier: "eso2007a",
                  title: "The Closest Black Hole to Earth",
                  credit: "ESO/L. Calçada",
                  explanation: "Artist's impression of HR 6819 — a triple system just 1,000 light-years away harbouring a dormant black hole, with the orbital paths of its two companion stars traced in colour.",
                  imageURL: "https://www.eso.org/public/archives/images/large/eso2007a.jpg",
                  thumbURL: "https://www.eso.org/public/archives/images/screen/eso2007a.jpg",
                  pageURL: "https://www.eso.org/public/images/eso2007a/",
                  dateString: "2020-05-06"),
            .init(identifier: "eso2210a",
                  title: "A Dormant Black Hole Unmasked",
                  credit: "ESO/L. Calçada",
                  explanation: "An artist's view of the first dormant stellar black hole confirmed outside the Milky Way — a dark void orbiting tight against a blazing blue giant in the Large Magellanic Cloud.",
                  imageURL: "https://www.eso.org/public/archives/images/large/eso2210a.jpg",
                  thumbURL: "https://www.eso.org/public/archives/images/screen/eso2210a.jpg",
                  pageURL: "https://www.eso.org/public/images/eso2210a/",
                  dateString: "2022-11-10"),
            .init(identifier: "eso2213a",
                  title: "Ultra-Hot Jupiter on a Close Orbit",
                  credit: "ESO/M. Kornmesser",
                  explanation: "An artist's impression of an ultra-hot Jupiter exoplanet locked in a scorching close orbit — temperatures above 3,000 K strip the planet's atmosphere away into space.",
                  imageURL: "https://www.eso.org/public/archives/images/large/eso2213a.jpg",
                  thumbURL: "https://www.eso.org/public/archives/images/screen/eso2213a.jpg",
                  pageURL: "https://www.eso.org/public/images/eso2213a/",
                  dateString: "2022-09-12"),
            .init(identifier: "eso0915a",
                  title: "Super-Earths of Gliese 667C",
                  credit: "ESO/L. Calçada",
                  explanation: "A barren rocky super-Earth looms in the foreground while a smaller ocean world hangs in the distance — both orbiting the red dwarf Gliese 667C in this cinematic artist's impression.",
                  imageURL: "https://www.eso.org/public/archives/images/large/eso0915a.jpg",
                  thumbURL: "https://www.eso.org/public/archives/images/screen/eso0915a.jpg",
                  pageURL: "https://www.eso.org/public/images/eso0915a/",
                  dateString: "2009-06-15"),
        ])

    /// Scientific artist impressions — exoplanets, compact objects, and
    /// discoveries rendered as 4K+ editorial-style space art.
    static let artistImpressions = StaticGallerySource(
        id: "artist-impressions", name: "Artist Impressions", subtitle: "Scientific concepts",
        symbol: "paintpalette.fill", accentHex: 0xFF6AD5,
        assets: [
            .init(identifier: "artists-proxima-b",
                  title: "Proxima b Surface",
                  credit: "ESO / M. Kornmesser",
                  explanation: "An artist's impression of the rocky exoplanet Proxima b orbiting the nearest star to the Sun.",
                  imageURL: "https://cdn.eso.org/images/large/eso1629a.jpg",
                  thumbURL: "https://cdn.eso.org/images/screen/eso1629a.jpg",
                  pageURL: "https://www.eso.org/public/images/eso1629a/"),
            .init(identifier: "artists-55-cancri-e",
                  title: "Lava World 55 Cancri e",
                  credit: "ESA/Hubble, M. Kornmesser",
                  explanation: "A 10K artist's concept of the super-Earth 55 Cancri e, a hot rocky planet with a partially molten surface.",
                  imageURL: "https://cdn.esahubble.org/archives/images/large/heic1603b.jpg",
                  thumbURL: "https://cdn.esahubble.org/archives/images/screen/heic1603b.jpg",
                  pageURL: "https://esahubble.org/images/heic1603b/"),
            .init(identifier: "artists-wasp-121b",
                  title: "WASP-121 b",
                  credit: "ESA/Hubble, M. Kornmesser",
                  explanation: "A hot Jupiter artist impression showing the strongly irradiated exoplanet WASP-121 b near its host star.",
                  imageURL: "https://cdn.esahubble.org/archives/images/large/heic2401a.jpg",
                  thumbURL: "https://cdn.esahubble.org/archives/images/screen/heic2401a.jpg",
                  pageURL: "https://esahubble.org/images/heic2401a/"),
            .init(identifier: "artists-k2-18b",
                  title: "K2-18 b",
                  credit: "ESA/Hubble, M. Kornmesser",
                  explanation: "A distant view of exoplanet K2-18 b and its red-dwarf host star in an artist's concept.",
                  imageURL: "https://cdn.esahubble.org/archives/images/large/heic1916a.jpg",
                  thumbURL: "https://cdn.esahubble.org/archives/images/screen/heic1916a.jpg",
                  pageURL: "https://esahubble.org/images/heic1916a/"),
            .init(identifier: "artists-gj-1132b",
                  title: "GJ 1132 b",
                  credit: "NASA, ESA, and R. Hurt (IPAC/Caltech)",
                  explanation: "A rocky exoplanet artist impression set against the Milky Way and its host star.",
                  imageURL: "https://cdn.esahubble.org/archives/images/large/heic2104a.jpg",
                  thumbURL: "https://cdn.esahubble.org/archives/images/screen/heic2104a.jpg",
                  pageURL: "https://esahubble.org/images/heic2104a/"),
            .init(identifier: "artists-neutron-star-merger",
                  title: "Neutron Star Merger",
                  credit: "ESO/L. Calcada/M. Kornmesser",
                  explanation: "An artist's impression of two merging neutron stars producing a bright kilonova.",
                  imageURL: "https://cdn.eso.org/images/large/eso1733a.jpg",
                  thumbURL: "https://cdn.eso.org/images/screen/eso1733a.jpg",
                  pageURL: "https://www.eso.org/public/images/eso1733a/"),
            .init(identifier: "artists-m87-black-hole",
                  title: "M87 Black Hole Concept",
                  credit: "ESO/M. Kornmesser",
                  explanation: "An artist's impression of the supermassive black hole at the center of Messier 87 and its hot accretion flow.",
                  imageURL: "https://cdn.eso.org/images/large/eso1907c.jpg",
                  thumbURL: "https://cdn.eso.org/images/screen/eso1907c.jpg",
                  pageURL: "https://www.eso.org/public/images/eso1907c/"),
            .init(identifier: "artists-hd-131399ab",
                  title: "HD 131399Ab",
                  credit: "ESO/L. Calcada",
                  explanation: "A triple-star exoplanet artist impression with three suns visible from a distant giant world.",
                  imageURL: "https://cdn.esahubble.org/archives/images/large/heic1619a.jpg",
                  thumbURL: "https://cdn.esahubble.org/archives/images/screen/heic1619a.jpg",
                  pageURL: "https://esahubble.org/images/heic1619a/"),
            .init(identifier: "artists-isolated-black-hole",
                  title: "Isolated Stellar-Mass Black Hole",
                  credit: "ESA/Hubble, Digitized Sky Survey, Nick Risinger, N. Bartmann",
                  explanation: "A Milky Way star field distorted by an isolated stellar-mass black hole in this artist's impression.",
                  imageURL: "https://cdn.esahubble.org/archives/images/large/heic2210a.jpg",
                  thumbURL: "https://cdn.esahubble.org/archives/images/screen/heic2210a.jpg",
                  pageURL: "https://esahubble.org/images/heic2210a/"),
            .init(title: "Surface of TRAPPIST-1f", nasaID: "PIA21423",
                  credit: "NASA/JPL-Caltech",
                  explanation: "An exoplanet surface concept with icy terrain, orange twilight, and neighboring TRAPPIST-1 worlds in the sky.",
                  dateString: "2017-06-01"),
            .init(identifier: "eso1733a-ai",
                  title: "Kilonova — Two Neutron Stars Collide",
                  credit: "ESO/L. Calçada/M. Kornmesser",
                  explanation: "An artist's impression of gravitational-wave event GW170817 — two neutron stars spiralling to a cataclysmic merger, forging gold and heavy elements in a brilliant blue-white kilonova flash.",
                  imageURL: "https://www.eso.org/public/archives/images/large/eso1733a.jpg",
                  thumbURL: "https://www.eso.org/public/archives/images/screen/eso1733a.jpg",
                  pageURL: "https://www.eso.org/public/images/eso1733a/",
                  dateString: "2017-10-16"),
            .init(identifier: "eso2007a-ai",
                  title: "Black Hole in a Triple Star System",
                  credit: "ESO/L. Calçada",
                  explanation: "An artist's impression of HR 6819: a dormant black hole caught silently orbiting within a triple star system — the closest known black hole to Earth.",
                  imageURL: "https://www.eso.org/public/archives/images/large/eso2007a.jpg",
                  thumbURL: "https://www.eso.org/public/archives/images/screen/eso2007a.jpg",
                  pageURL: "https://www.eso.org/public/images/eso2007a/",
                  dateString: "2020-05-06"),
            .init(identifier: "eso2213a-ai",
                  title: "Ultra-Hot Jupiter on a Close Orbit",
                  credit: "ESO/M. Kornmesser",
                  explanation: "A photorealistic artist impression of a gas giant on an extreme close orbit, its atmosphere blazing at over 3,000 K and being slowly stripped away by the host star's radiation.",
                  imageURL: "https://www.eso.org/public/archives/images/large/eso2213a.jpg",
                  thumbURL: "https://www.eso.org/public/archives/images/screen/eso2213a.jpg",
                  pageURL: "https://www.eso.org/public/images/eso2213a/",
                  dateString: "2022-09-12"),
            .init(identifier: "eso0915a-ai",
                  title: "Super-Earths of Gliese 667C",
                  credit: "ESO/L. Calçada",
                  explanation: "An artist's impression of the Gliese 667C planetary system: a barren rocky super-Earth in the foreground, a habitable ocean world in the distance, under the glow of a red dwarf sun.",
                  imageURL: "https://www.eso.org/public/archives/images/large/eso0915a.jpg",
                  thumbURL: "https://www.eso.org/public/archives/images/screen/eso0915a.jpg",
                  pageURL: "https://www.eso.org/public/images/eso0915a/",
                  dateString: "2009-06-15"),
        ])
}
